name: Build and push Docker image for staging/development environment

permissions:
  contents: read
on:
  push:
    branches:
      - dev
      - development
      - stage
      - staging

jobs:
  docker-build-push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short=7 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: echo Short SHA
        run: echo $SHORT_SHA
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.EO_PROJ_STAGING_DOCKER_REGISTRY_URL}}
          username: ${{ secrets.EO_PROJ_STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.EO_PROJ_STAGING_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image under tag ${{ env.SHORT_SHA }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ secrets.EO_PROJ_STAGING_DOCKER_REGISTRY_URL }}/stac-browser:cache
          cache-to: type=registry,ref=${{ secrets.EO_PROJ_STAGING_DOCKER_REGISTRY_URL }}/stac-browser:cache,mode=max
          push: true
          tags: ${{ secrets.EO_PROJ_STAGING_DOCKER_REGISTRY_URL }}/stac-browser:${{ env.SHORT_SHA }}
          build-args: |
            catalog_url = ${{ secrets.STAC_BROWSER_CATALOG_URL }}